import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const { NODE_ENV, PORT, MONGODB_URI, SECRET_KEY, LOG_FORMAT, LOG_DIR, ORIGIN, JWT_ACCESS_EXPIRATION_MINUTES, JWT_REFRESH_EXPIRATION_DAYS,JWT_RESET_PASSWORD_EXPIRATION_MINUTES,JWT_VERIFY_EMAIL_EXPIRATION_MINUTES,SMTP_HOST,SMTP_PORT,SMTP_USERNAME,SMTP_PASSWORD,EMAIL_FROM, DOMAIN_URL} = process.env;
